export const HERO_IMAGE = "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1400";

const imgs = {
  ai1: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
  ai2: "https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&q=80&w=800",
  gaming1: "https://images.unsplash.com/photo-1587831990711-23ca6441447b?auto=format&fit=crop&q=80&w=800",
  gaming2: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800",
  gaming3: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&q=80&w=800",
  ev1: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=800",
  ev2: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800",
  ev3: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=800",
  gadget1: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800",
  gadget2: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800",
  vr1: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?auto=format&fit=crop&q=80&w=800",
  setup: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&q=80&w=800",
  code: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
  space: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&q=80&w=800",
  handheld: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&q=80&w=800",
  car_interior: "https://images.unsplash.com/photo-1611016186353-9af58c69a533?auto=format&fit=crop&q=80&w=800"
};

export const featuredArticles = [
  {
    id: 1,
    title: "Slik endrer AI arbeidshverdagen i 2026: Her er verktøyene du må kunne",
    excerpt: "Eksperter spår massive endringer. Vi har testet de nye tjenestene som faktisk kutter tidsbruken din i to.",
    author: "Jonas Berg",
    time: "2 timer siden",
    readTime: "4 min",
    comments: 42,
    category: "AI",
    type: "standard",
    image: imgs.ai1,
  },
  {
    id: 2,
    title: "Steam Deck 2 lekket: Får OLED-skjerm og dobling av ytelse",
    excerpt: "Nye spesifikasjoner peker mot en kraftig oppgradering for Valves populære håndholdte maskin.",
    author: "Erik Sørheim",
    time: "4 timer siden",
    readTime: "3 min",
    comments: 128,
    category: "Gaming",
    type: "standard",
    image: imgs.handheld,
  },
  {
    id: 3,
    title: "TEST: Polestar 4 Long Range – Utfordrer Tesla på rekkevidde",
    excerpt: "Vi kjørte bilen over fjellet i minusgrader. Den leverer varene, men mangelen på bakrute krever tilvenning.",
    author: "Maria Øverland",
    time: "6 timer siden",
    readTime: "8 min",
    comments: 215,
    category: "Tester",
    type: "test",
    score: "8.5/10",
    image: imgs.ev1,
  },
  {
    id: 4,
    title: "Slik velger du riktig støydemping i åpent landskap",
    excerpt: "Sony, Bose eller Apple? Vi har testet markedets beste hodetelefoner i støyende kontormiljøer.",
    author: "Lars Pettersen",
    time: "8 timer siden",
    readTime: "6 min",
    comments: 54,
    category: "Guider",
    type: "guide",
    image: imgs.gadget2,
  },
];

export const latestArticles = [
  {
    id: 5,
    title: "Cyberpunk 2077 får AI-oppdatering til NPC-er: Nå kan du snakke med alle",
    excerpt: "CD Projekt Red integrerer ekte språkmodeller i Night City.",
    author: "Nora Kven",
    time: "10 timer siden",
    readTime: "3 min",
    comments: 89,
    category: "Gaming",
    type: "standard",
    image: imgs.gaming1,
  },
  {
    id: 6,
    title: "Se Volkswagens nye ID.2all: Skal koste under 250.000 kroner",
    excerpt: "Endelig kommer den billige folke-elbilen.",
    author: "Svein Haug",
    time: "12 timer siden",
    readTime: "5 min",
    duration: "04:12",
    comments: 312,
    category: "Elbil",
    type: "video",
    image: imgs.ev3,
  },
  {
    id: 7,
    title: "TEST: Apple Vision Pro 2 – Er den verdt prisen?",
    excerpt: "Brillene er lettere og billigere, men det er fortsatt et luksusprodukt.",
    author: "Ida Strøm",
    time: "14 timer siden",
    readTime: "12 min",
    comments: 156,
    category: "Tester",
    type: "test",
    score: "9.0/10",
    image: imgs.vr1,
  },
  {
    id: 8,
    title: "Guide: Sikre hjemmenettverket ditt på 10 minutter",
    excerpt: "Slik stenger du hackere ute fra smarthjemmet.",
    author: "Petter Moen",
    time: "16 timer siden",
    readTime: "4 min",
    comments: 23,
    category: "Guider",
    type: "guide",
    image: imgs.code,
  },
  {
    id: 9,
    title: "OpenAI slipper ny API-plattform spesialisert for norsk språk",
    excerpt: "Gjør det enklere for norske bedrifter å implementere AI.",
    author: "Camilla Vik",
    time: "18 timer siden",
    readTime: "2 min",
    comments: 12,
    category: "AI",
    type: "standard",
    image: imgs.ai2,
  },
  {
    id: 10,
    title: "Bygg fremtidens skyløsninger sikrere og raskere med Azure",
    excerpt: "Integrer AI sømløst i dine eksisterende prosesser.",
    author: "Microsoft Norge",
    time: "1 dag siden",
    readTime: "3 min",
    comments: 0,
    category: "Gadgets",
    type: "sponsored",
    image: imgs.setup,
  },
  {
    id: 11,
    title: "Rykter: PlayStation 6 kan få lansering allerede i 2027",
    excerpt: "Lekkasjer fra AMD tyder på at Sony fremskynder planene.",
    author: "Thomas Lund",
    time: "1 dag siden",
    readTime: "5 min",
    comments: 341,
    category: "Gaming",
    type: "standard",
    image: imgs.gaming2,
  },
  {
    id: 12,
    title: "TEST: Samsung Galaxy S26 Ultra slår knockout på Apple",
    excerpt: "Kameraet setter en ny standard for mobilfotografering.",
    author: "Roald Næss",
    time: "2 dager siden",
    readTime: "9 min",
    comments: 112,
    category: "Tester",
    type: "test",
    score: "9.5/10",
    image: imgs.gadget1,
  },
  {
    id: 13,
    title: "Årets 10 mest ventede spill: Dette MÅ du spille",
    excerpt: "Gled deg til et stappfullt spillår.",
    author: "Kaja Ruud",
    time: "3 dager siden",
    readTime: "7 min",
    duration: "10:30",
    comments: 88,
    category: "Gaming",
    type: "video",
    image: imgs.gaming3,
  },
  {
    id: 14,
    title: "TEST: Xpeng G9 knuser europeiske rivaler på ladehastighet",
    excerpt: "Premium SUV fra Kina som leverer varene.",
    author: "Henrik Vold",
    time: "4 dager siden",
    readTime: "11 min",
    comments: 412,
    category: "Tester",
    type: "test",
    score: "8.0/10",
    image: imgs.ev2,
  },
  {
    id: 15,
    title: "Slik lager du fotorealistiske AI-bilder med Midjourney v6",
    excerpt: "En komplett guide fra nybegynner til proff prompts-skriver.",
    author: "Line Haug",
    time: "5 dager siden",
    readTime: "15 min",
    comments: 45,
    category: "Guider",
    type: "guide",
    image: imgs.ai1,
  },
  {
    id: 16,
    title: "Nvidia RTX 5090 lansert: Koster ufattelige 32 000 kroner",
    excerpt: "Den nye toppmodellen slår alle rekorder – inkludert prisrekorden.",
    author: "Andreas Mo",
    time: "5 dager siden",
    readTime: "6 min",
    comments: 567,
    category: "Gadgets",
    type: "standard",
    image: imgs.gaming1,
  }
];

export const testArticlesData = [
  latestArticles.find(a => a.id === 7),
  latestArticles.find(a => a.id === 12),
  latestArticles.find(a => a.id === 14),
  featuredArticles.find(a => a.id === 3),
  {
    id: 17,
    title: "TEST: ASUS ROG Zephyrus G16 (2026)",
    excerpt: "Kanskje den fineste gaming-laptopen vi har testet. En drøm for innholdsskapere.",
    author: "Erik Sørheim",
    time: "1 uke siden",
    readTime: "8 min",
    comments: 76,
    category: "Tester",
    type: "test",
    score: "9.0/10",
    image: imgs.setup,
  }
];

export const guideArticlesData = [
  featuredArticles.find(a => a.id === 4),
  latestArticles.find(a => a.id === 8),
  latestArticles.find(a => a.id === 15),
  {
    id: 18,
    title: "Slik velger du riktig gaming-PC: Hva trenger du egentlig?",
    excerpt: "Ikke betal for ytelse du aldri kommer til å bruke.",
    author: "Thomas Lund",
    time: "2 uker siden",
    readTime: "10 min",
    comments: 112,
    category: "Guider",
    type: "guide",
    image: imgs.gaming2,
  },
  {
    id: 19,
    title: "Dette MÅ du sjekke før du kjøper elbil på bruktmarkedet",
    excerpt: "Unngå de dyreste fellene på Finn.no.",
    author: "Svein Haug",
    time: "3 uker siden",
    readTime: "8 min",
    comments: 230,
    category: "Guider",
    type: "guide",
    image: imgs.car_interior,
  }
];

export const gamingArticlesData = [
  featuredArticles.find(a => a.id === 2),
  latestArticles.find(a => a.id === 5),
  latestArticles.find(a => a.id === 11),
  latestArticles.find(a => a.id === 13),
  testArticlesData.find(a => a.id === 17)
];

export const evArticlesData = [
  featuredArticles.find(a => a.id === 3),
  latestArticles.find(a => a.id === 6),
  latestArticles.find(a => a.id === 14),
  {
    id: 21,
    title: "Tesla Model Y 'Juniper' observert uten maskering",
    excerpt: "Den oppgraderte versjonen nærmer seg produksjon.",
    author: "Henrik Vold",
    time: "2 uker siden",
    readTime: "4 min",
    comments: 432,
    category: "Elbil",
    type: "standard",
    image: imgs.ev1,
  },
  {
    id: 22,
    title: "TEST: Volkswagen ID.7 er endelig den passaten vi har ventet på",
    excerpt: "Tyskerne slår tilbake med knallgod komfort og lang rekkevidde.",
    author: "Maria Øverland",
    time: "3 uker siden",
    readTime: "14 min",
    comments: 654,
    category: "Tester",
    type: "test",
    score: "8.5/10",
    image: imgs.ev2,
  },
  guideArticlesData.find(a => a.id === 19)
];

export const aiArticlesData = [
  featuredArticles.find(a => a.id === 1),
  latestArticles.find(a => a.id === 9),
  guideArticlesData.find(a => a.id === 15),
  {
    id: 23,
    title: "Slik avslører du AI-genererte bilder på 5 sekunder",
    excerpt: "Verktøyene er gode, men disse feilene går alltid igjen.",
    author: "Jonas Berg",
    time: "2 uker siden",
    readTime: "5 min",
    duration: "02:15",
    comments: 34,
    category: "AI",
    type: "video",
    image: imgs.ai2,
  },
  {
    id: 24,
    title: "Ny norsk språkmodell knuser GPT-4 på nynorsk",
    excerpt: "Forskere har knekt koden for norske dialekter.",
    author: "Camilla Vik",
    time: "1 måned siden",
    readTime: "4 min",
    comments: 110,
    category: "AI",
    type: "standard",
    image: imgs.code,
  },
  {
    id: 25,
    title: "Google lanserer 'Project Astra' – fremtidens AI-assistent for mobil",
    excerpt: "Den ser og forstår verden rundt deg i sanntid gjennom kameraet ditt.",
    author: "Jonas Berg",
    time: "2 måneder siden",
    readTime: "6 min",
    comments: 215,
    category: "AI",
    type: "standard",
    image: imgs.gadget1,
  }
];

export const trendingArticles = [
  { id: 101, title: "GTA VI: Ny trailer bekrefter lanseringsdatoen for julen 2026", category: "Gaming", readTime: "2 min", comments: 980 },
  { id: 102, title: "TEST: Samsung Galaxy S26 Ultra slår knockout på konkurrentene", category: "Tester", readTime: "9 min", comments: 112 },
  { id: 103, title: "Nye regler for elbil-støtte: Dette betyr det for lommeboken din", category: "Elbil", readTime: "5 min", comments: 312 },
  { id: 104, title: "Nvidia RTX 5090 lansert: Er den verdt svimlende 32 000 kroner?", category: "Gadgets", readTime: "6 min", comments: 567 },
  { id: 105, title: "7 smarte AI-verktøy som faktisk sparer deg tid på kontoret", category: "Guider", readTime: "4 min", comments: 88 },
  { id: 106, title: "Steam Deck 2 lekket: Får etterlengtet oppgradering", category: "Gaming", readTime: "3 min", comments: 128 },
];

export const allArticles = [...featuredArticles, ...latestArticles];
