import { getBillingPlan } from "./billing-plans.js";

const premiumMonthly = getBillingPlan("premium_monthly");
const premiumYearly = getBillingPlan("premium_yearly");

export const subscriptionPlans = [
  {
    id: "free",
    name: "Gratis",
    slug: "free",
    description: "For nybegynnere",
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: "NOK",
    features: [
      "Les åpne artikler",
      "Lagre artikler",
      "Motta nyhetsbrev",
      "Grunnleggende profilside",
    ],
    isPopular: false,
    isActive: true,
    sortOrder: 1,
    ctaText: "Nåværende plan",
  },
  {
    id: "pluss",
    name: "TEKKNO Pluss",
    slug: "pluss",
    description: "For den bevisste leseren",
    monthlyPrice: 199,
    yearlyPrice: 1990,
    currency: "NOK",
    features: [
      "Tilgang til alle plussaker",
      "Reklamelett leseopplevelse",
      "Lagrede artikler",
      "Nyhetsbrev for AI, teknologi og gaming",
      "Eksklusive analyser og guider",
    ],
    isPopular: true,
    isActive: true,
    sortOrder: 2,
    ctaText: "Oppgrader til Pluss",
  },
  {
    id: "premium",
    planKey: "premium_monthly",
    yearlyPlanKey: "premium_yearly",
    name: "TEKKNO Premium",
    slug: "premium",
    description: "For ekspertene",
    monthlyPrice: premiumMonthly.price,
    yearlyPrice: premiumYearly.price,
    currency: premiumMonthly.currency,
    entitlementKey: premiumMonthly.entitlementKey,
    features: [
      "Alt i Pluss",
      "Tidlig tilgang til tester og guider",
      "Eksklusive premium-artikler",
      "Dypdykk og longreads",
      "Prioritert support",
      "Invitasjon til digitale arrangementer/webinarer",
    ],
    isPopular: false,
    isActive: true,
    sortOrder: 3,
    ctaText: "Oppgrader til Premium",
  },
  {
    id: "familie",
    name: "TEKKNO Familie",
    slug: "familie",
    description: "For hele husstanden",
    monthlyPrice: 199,
    yearlyPrice: 1990,
    currency: "NOK",
    features: [
      "Alt i Pluss",
      "Opptil 4 brukere",
      "Familie-/husstandstilgang",
      "Administrasjon av familiemedlemmer",
    ],
    isPopular: false,
    isActive: true,
    sortOrder: 4,
    ctaText: "Velg Familie",
  },
  {
    id: "bedrift",
    name: "TEKKNO Bedrift",
    slug: "bedrift",
    description: "For team og bedrifter",
    monthlyPrice: 499,
    yearlyPrice: 4990,
    currency: "NOK",
    features: [
      "Tilgang for flere ansatte",
      "Bedriftsfaktura",
      "Administrasjon av brukere",
      "Egne bedriftsvilkår",
      "Kontakt salg/redaksjon",
    ],
    isPopular: false,
    isActive: true,
    sortOrder: 5,
    ctaText: "Kontakt oss",
    isContactRequired: true,
  },
];

export function getPlanBySlug(slug) {
  return subscriptionPlans.find((p) => p.slug === slug);
}
