/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'payload-users': PayloadUserAuthOperations;
  };
  blocks: {};
  collections: {
    'payload-users': PayloadUser;
    'media-assets': MediaAsset;
    categories: Category;
    authors: Author;
    articles: Article;
    'frontpage-slots': FrontpageSlot;
    reels: Reel;
    'tip-submissions': TipSubmission;
    'ad-campaigns': AdCampaign;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'payload-users': PayloadUsersSelect<false> | PayloadUsersSelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'frontpage-slots': FrontpageSlotsSelect<false> | FrontpageSlotsSelect<true>;
    reels: ReelsSelect<false> | ReelsSelect<true>;
    'tip-submissions': TipSubmissionsSelect<false> | TipSubmissionsSelect<true>;
    'ad-campaigns': AdCampaignsSelect<false> | AdCampaignsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: PayloadUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PayloadUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users".
 */
export interface PayloadUser {
  id: number;
  name: string;
  roles: ('journalist' | 'editor' | 'admin' | 'desk' | 'moderator' | 'ad_manager')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'payload-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: number;
  title: string;
  provider: 'cloudflare_images' | 'cloudflare_stream' | 'r2' | 'external';
  type: 'image' | 'video' | 'file';
  cloudflareImageId?: string | null;
  cloudflareStreamUid?: string | null;
  deliveryUrl?: string | null;
  thumbnailUrl?: string | null;
  originalFilename?: string | null;
  width?: number | null;
  height?: number | null;
  duration?: number | null;
  alt?: string | null;
  caption?: string | null;
  credit?: string | null;
  status: 'draft' | 'uploading' | 'processing' | 'ready' | 'failed';
  usageRights?: string | null;
  uploadedBy?: (number | null) | PayloadUser;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payload-owned sections and categories for the newspaper.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  existingRoute?: ('/ai' | '/gaming' | '/elbil' | '/gadgets' | '/tester' | '/guider' | '/video') | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payload-owned public author and journalist profiles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  profileImage?: (number | null) | MediaAsset;
  email?: string | null;
  title?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payload-owned articles. Payload is the source of truth for editorial content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: string | null;
  status: 'draft' | 'review' | 'scheduled' | 'published' | 'archived';
  publishedAt?: string | null;
  scheduledAt?: string | null;
  authors?: (number | Author)[] | null;
  categories?: (number | Category)[] | null;
  heroMedia?: (number | null) | MediaAsset;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | MediaAsset;
  canonicalUrl?: string | null;
  isBreaking?: boolean | null;
  isFeatured?: boolean | null;
  accessLevel: 'public' | 'members' | 'paid';
  newsletterEligible?: boolean | null;
  paywallEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frontpage-slots".
 */
export interface FrontpageSlot {
  id: number;
  /**
   * Legacy database compatibility field. Use slotName for editors.
   */
  label: string;
  slotName: string;
  /**
   * Legacy database compatibility field. Use placement and priority for editors.
   */
  slot: 'hero-main' | 'hero-secondary' | 'latest' | 'reels' | 'editorial-block';
  placement: 'hero' | 'top_story' | 'section_feature' | 'opinion' | 'video' | 'ad';
  article?: (number | null) | Article;
  mediaAsset?: (number | null) | MediaAsset;
  manualTitleOverride?: string | null;
  manualExcerptOverride?: string | null;
  priority: number;
  /**
   * Legacy database compatibility field. Use priority for editors.
   */
  position: number;
  startsAt?: string | null;
  expiresAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels".
 */
export interface Reel {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published' | 'archived';
  mediaAsset: number | MediaAsset;
  article?: (number | null) | Article;
  cloudflareStreamUid?: string | null;
  description?: string | null;
  publishedAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tip-submissions".
 */
export interface TipSubmission {
  id: number;
  title: string;
  message: string;
  category?: string | null;
  submittedByName?: string | null;
  submittedByEmail?: string | null;
  phone?: string | null;
  status: 'new' | 'reviewing' | 'contacted' | 'rejected' | 'converted_to_story';
  assignedTo?: (number | null) | PayloadUser;
  relatedArticle?: (number | null) | Article;
  internalNotes?: string | null;
  riskLevel: 'low' | 'medium' | 'high';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-campaigns".
 */
export interface AdCampaign {
  id: number;
  title: string;
  placement: string;
  mediaAsset?: (number | null) | MediaAsset;
  targetUrl: string;
  startsAt?: string | null;
  endsAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'payload-users';
        value: number | PayloadUser;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: number | MediaAsset;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'frontpage-slots';
        value: number | FrontpageSlot;
      } | null)
    | ({
        relationTo: 'reels';
        value: number | Reel;
      } | null)
    | ({
        relationTo: 'tip-submissions';
        value: number | TipSubmission;
      } | null)
    | ({
        relationTo: 'ad-campaigns';
        value: number | AdCampaign;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'payload-users';
    value: number | PayloadUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'payload-users';
    value: number | PayloadUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-users_select".
 */
export interface PayloadUsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  title?: T;
  provider?: T;
  type?: T;
  cloudflareImageId?: T;
  cloudflareStreamUid?: T;
  deliveryUrl?: T;
  thumbnailUrl?: T;
  originalFilename?: T;
  width?: T;
  height?: T;
  duration?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  status?: T;
  usageRights?: T;
  uploadedBy?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  parent?: T;
  existingRoute?: T;
  seoTitle?: T;
  seoDescription?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  profileImage?: T;
  email?: T;
  title?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  scheduledAt?: T;
  authors?: T;
  categories?: T;
  heroMedia?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  canonicalUrl?: T;
  isBreaking?: T;
  isFeatured?: T;
  accessLevel?: T;
  newsletterEligible?: T;
  paywallEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frontpage-slots_select".
 */
export interface FrontpageSlotsSelect<T extends boolean = true> {
  label?: T;
  slotName?: T;
  slot?: T;
  placement?: T;
  article?: T;
  mediaAsset?: T;
  manualTitleOverride?: T;
  manualExcerptOverride?: T;
  priority?: T;
  position?: T;
  startsAt?: T;
  expiresAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reels_select".
 */
export interface ReelsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  mediaAsset?: T;
  article?: T;
  cloudflareStreamUid?: T;
  description?: T;
  publishedAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tip-submissions_select".
 */
export interface TipSubmissionsSelect<T extends boolean = true> {
  title?: T;
  message?: T;
  category?: T;
  submittedByName?: T;
  submittedByEmail?: T;
  phone?: T;
  status?: T;
  assignedTo?: T;
  relatedArticle?: T;
  internalNotes?: T;
  riskLevel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-campaigns_select".
 */
export interface AdCampaignsSelect<T extends boolean = true> {
  title?: T;
  placement?: T;
  mediaAsset?: T;
  targetUrl?: T;
  startsAt?: T;
  endsAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}