/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  serial,
  varchar,
  timestamp,
  numeric,
  jsonb,
  type AnyPgColumn,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_payload_users_roles = pgEnum("enum_payload_users_roles", [
  "journalist",
  "editor",
  "admin",
  "desk",
  "moderator",
  "ad_manager",
]);
export const enum_media_assets_provider = pgEnum("enum_media_assets_provider", [
  "cloudflare_images",
  "cloudflare_stream",
  "r2",
  "external",
]);
export const enum_media_assets_type = pgEnum("enum_media_assets_type", [
  "image",
  "video",
  "file",
]);
export const enum_media_assets_status = pgEnum("enum_media_assets_status", [
  "draft",
  "uploading",
  "processing",
  "ready",
  "failed",
]);
export const enum_categories_existing_route = pgEnum(
  "enum_categories_existing_route",
  ["/ai", "/gaming", "/elbil", "/gadgets", "/tester", "/guider", "/video"],
);
export const enum_articles_status = pgEnum("enum_articles_status", [
  "draft",
  "review",
  "scheduled",
  "published",
  "archived",
]);
export const enum_articles_access_level = pgEnum("enum_articles_access_level", [
  "public",
  "members",
  "paid",
]);
export const enum_frontpage_slots_placement = pgEnum(
  "enum_frontpage_slots_placement",
  ["hero", "top_story", "section_feature", "opinion", "video", "ad"],
);
export const enum_reels_status = pgEnum("enum_reels_status", [
  "draft",
  "published",
  "archived",
]);
export const enum_tip_submissions_status = pgEnum(
  "enum_tip_submissions_status",
  ["new", "reviewing", "contacted", "rejected", "converted_to_story"],
);
export const enum_tip_submissions_risk_level = pgEnum(
  "enum_tip_submissions_risk_level",
  ["low", "medium", "high"],
);

export const payload_users_roles = pgTable(
  "payload_users_roles",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_payload_users_roles("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("payload_users_roles_order_idx").on(columns.order),
    index("payload_users_roles_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_users.id],
      name: "payload_users_roles_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_users_sessions = pgTable(
  "payload_users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("payload_users_sessions_order_idx").on(columns._order),
    index("payload_users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [payload_users.id],
      name: "payload_users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_users = pgTable(
  "payload_users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("payload_users_updated_at_idx").on(columns.updatedAt),
    index("payload_users_created_at_idx").on(columns.createdAt),
    uniqueIndex("payload_users_email_idx").on(columns.email),
  ],
);

export const media_assets = pgTable(
  "media_assets",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    provider: enum_media_assets_provider("provider")
      .notNull()
      .default("cloudflare_images"),
    type: enum_media_assets_type("type").notNull(),
    cloudflareImageId: varchar("cloudflare_image_id"),
    cloudflareStreamUid: varchar("cloudflare_stream_uid"),
    deliveryUrl: varchar("delivery_url"),
    thumbnailUrl: varchar("thumbnail_url"),
    originalFilename: varchar("original_filename"),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    duration: numeric("duration", { mode: "number" }),
    alt: varchar("alt"),
    caption: varchar("caption"),
    credit: varchar("credit"),
    status: enum_media_assets_status("status").notNull().default("draft"),
    usageRights: varchar("usage_rights"),
    uploadedBy: integer("uploaded_by_id").references(() => payload_users.id, {
      onDelete: "set null",
    }),
    metadata: jsonb("metadata"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("media_assets_cloudflare_image_id_idx").on(columns.cloudflareImageId),
    index("media_assets_cloudflare_stream_uid_idx").on(
      columns.cloudflareStreamUid,
    ),
    index("media_assets_uploaded_by_idx").on(columns.uploadedBy),
    index("media_assets_updated_at_idx").on(columns.updatedAt),
    index("media_assets_created_at_idx").on(columns.createdAt),
  ],
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    description: varchar("description"),
    parent: integer("parent_id").references((): AnyPgColumn => categories.id, {
      onDelete: "set null",
    }),
    existingRoute: enum_categories_existing_route("existing_route"),
    seoTitle: varchar("seo_title"),
    seoDescription: varchar("seo_description"),
    sortOrder: numeric("sort_order", { mode: "number" }).default(0),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("categories_slug_idx").on(columns.slug),
    index("categories_parent_idx").on(columns.parent),
    index("categories_updated_at_idx").on(columns.updatedAt),
    index("categories_created_at_idx").on(columns.createdAt),
  ],
);

export const authors = pgTable(
  "authors",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    slug: varchar("slug").notNull(),
    bio: varchar("bio"),
    profileImage: integer("profile_image_id").references(
      () => media_assets.id,
      {
        onDelete: "set null",
      },
    ),
    email: varchar("email"),
    title: varchar("title"),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("authors_slug_idx").on(columns.slug),
    index("authors_profile_image_idx").on(columns.profileImage),
    index("authors_updated_at_idx").on(columns.updatedAt),
    index("authors_created_at_idx").on(columns.createdAt),
  ],
);

export const articles = pgTable(
  "articles",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    excerpt: varchar("excerpt"),
    content: varchar("content"),
    status: enum_articles_status("status").notNull().default("draft"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    scheduledAt: timestamp("scheduled_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    heroMedia: integer("hero_media_id").references(() => media_assets.id, {
      onDelete: "set null",
    }),
    seoTitle: varchar("seo_title"),
    seoDescription: varchar("seo_description"),
    seoImage: integer("seo_image_id").references(() => media_assets.id, {
      onDelete: "set null",
    }),
    canonicalUrl: varchar("canonical_url"),
    isBreaking: boolean("is_breaking").default(false),
    isFeatured: boolean("is_featured").default(false),
    accessLevel: enum_articles_access_level("access_level")
      .notNull()
      .default("public"),
    newsletterEligible: boolean("newsletter_eligible").default(false),
    paywallEnabled: boolean("paywall_enabled").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("articles_slug_idx").on(columns.slug),
    index("articles_hero_media_idx").on(columns.heroMedia),
    index("articles_seo_image_idx").on(columns.seoImage),
    index("articles_updated_at_idx").on(columns.updatedAt),
    index("articles_created_at_idx").on(columns.createdAt),
  ],
);

export const articles_rels = pgTable(
  "articles_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    authorsID: integer("authors_id"),
    categoriesID: integer("categories_id"),
  },
  (columns) => [
    index("articles_rels_order_idx").on(columns.order),
    index("articles_rels_parent_idx").on(columns.parent),
    index("articles_rels_path_idx").on(columns.path),
    index("articles_rels_authors_id_idx").on(columns.authorsID),
    index("articles_rels_categories_id_idx").on(columns.categoriesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [articles.id],
      name: "articles_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["authorsID"]],
      foreignColumns: [authors.id],
      name: "articles_rels_authors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "articles_rels_categories_fk",
    }).onDelete("cascade"),
  ],
);

export const frontpage_slots = pgTable(
  "frontpage_slots",
  {
    id: serial("id").primaryKey(),
    slotName: varchar("slot_name").notNull(),
    placement: enum_frontpage_slots_placement("placement").notNull(),
    article: integer("article_id").references(() => articles.id, {
      onDelete: "set null",
    }),
    mediaAsset: integer("media_asset_id").references(() => media_assets.id, {
      onDelete: "set null",
    }),
    manualTitleOverride: varchar("manual_title_override"),
    manualExcerptOverride: varchar("manual_excerpt_override"),
    priority: numeric("priority", { mode: "number" }).notNull().default(1),
    startsAt: timestamp("starts_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("frontpage_slots_article_idx").on(columns.article),
    index("frontpage_slots_media_asset_idx").on(columns.mediaAsset),
    index("frontpage_slots_updated_at_idx").on(columns.updatedAt),
    index("frontpage_slots_created_at_idx").on(columns.createdAt),
  ],
);

export const reels = pgTable(
  "reels",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    slug: varchar("slug").notNull(),
    status: enum_reels_status("status").notNull().default("draft"),
    mediaAsset: integer("media_asset_id")
      .notNull()
      .references(() => media_assets.id, {
        onDelete: "set null",
      }),
    article: integer("article_id").references(() => articles.id, {
      onDelete: "set null",
    }),
    cloudflareStreamUid: varchar("cloudflare_stream_uid"),
    description: varchar("description"),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    isActive: boolean("is_active").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("reels_slug_idx").on(columns.slug),
    index("reels_media_asset_idx").on(columns.mediaAsset),
    index("reels_article_idx").on(columns.article),
    index("reels_cloudflare_stream_uid_idx").on(columns.cloudflareStreamUid),
    index("reels_updated_at_idx").on(columns.updatedAt),
    index("reels_created_at_idx").on(columns.createdAt),
  ],
);

export const tip_submissions = pgTable(
  "tip_submissions",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    message: varchar("message").notNull(),
    category: varchar("category"),
    submittedByName: varchar("submitted_by_name"),
    submittedByEmail: varchar("submitted_by_email"),
    phone: varchar("phone"),
    status: enum_tip_submissions_status("status").notNull().default("new"),
    assignedTo: integer("assigned_to_id").references(() => payload_users.id, {
      onDelete: "set null",
    }),
    relatedArticle: integer("related_article_id").references(
      () => articles.id,
      {
        onDelete: "set null",
      },
    ),
    internalNotes: varchar("internal_notes"),
    riskLevel: enum_tip_submissions_risk_level("risk_level")
      .notNull()
      .default("low"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("tip_submissions_assigned_to_idx").on(columns.assignedTo),
    index("tip_submissions_related_article_idx").on(columns.relatedArticle),
    index("tip_submissions_updated_at_idx").on(columns.updatedAt),
    index("tip_submissions_created_at_idx").on(columns.createdAt),
  ],
);

export const ad_campaigns = pgTable(
  "ad_campaigns",
  {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    placement: varchar("placement").notNull(),
    mediaAsset: integer("media_asset_id").references(() => media_assets.id, {
      onDelete: "set null",
    }),
    targetUrl: varchar("target_url").notNull(),
    startsAt: timestamp("starts_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    endsAt: timestamp("ends_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    isActive: boolean("is_active").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("ad_campaigns_media_asset_idx").on(columns.mediaAsset),
    index("ad_campaigns_updated_at_idx").on(columns.updatedAt),
    index("ad_campaigns_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "payload-usersID": integer("payload_users_id"),
    "media-assetsID": integer("media_assets_id"),
    categoriesID: integer("categories_id"),
    authorsID: integer("authors_id"),
    articlesID: integer("articles_id"),
    "frontpage-slotsID": integer("frontpage_slots_id"),
    reelsID: integer("reels_id"),
    "tip-submissionsID": integer("tip_submissions_id"),
    "ad-campaignsID": integer("ad_campaigns_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_payload_users_id_idx").on(
      columns["payload-usersID"],
    ),
    index("payload_locked_documents_rels_media_assets_id_idx").on(
      columns["media-assetsID"],
    ),
    index("payload_locked_documents_rels_categories_id_idx").on(
      columns.categoriesID,
    ),
    index("payload_locked_documents_rels_authors_id_idx").on(columns.authorsID),
    index("payload_locked_documents_rels_articles_id_idx").on(
      columns.articlesID,
    ),
    index("payload_locked_documents_rels_frontpage_slots_id_idx").on(
      columns["frontpage-slotsID"],
    ),
    index("payload_locked_documents_rels_reels_id_idx").on(columns.reelsID),
    index("payload_locked_documents_rels_tip_submissions_id_idx").on(
      columns["tip-submissionsID"],
    ),
    index("payload_locked_documents_rels_ad_campaigns_id_idx").on(
      columns["ad-campaignsID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-usersID"]],
      foreignColumns: [payload_users.id],
      name: "payload_locked_documents_rels_payload_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["media-assetsID"]],
      foreignColumns: [media_assets.id],
      name: "payload_locked_documents_rels_media_assets_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["authorsID"]],
      foreignColumns: [authors.id],
      name: "payload_locked_documents_rels_authors_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["articlesID"]],
      foreignColumns: [articles.id],
      name: "payload_locked_documents_rels_articles_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["frontpage-slotsID"]],
      foreignColumns: [frontpage_slots.id],
      name: "payload_locked_documents_rels_frontpage_slots_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["reelsID"]],
      foreignColumns: [reels.id],
      name: "payload_locked_documents_rels_reels_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["tip-submissionsID"]],
      foreignColumns: [tip_submissions.id],
      name: "payload_locked_documents_rels_tip_submissions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["ad-campaignsID"]],
      foreignColumns: [ad_campaigns.id],
      name: "payload_locked_documents_rels_ad_campaigns_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "payload-usersID": integer("payload_users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_payload_users_id_idx").on(
      columns["payload-usersID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-usersID"]],
      foreignColumns: [payload_users.id],
      name: "payload_preferences_rels_payload_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_payload_users_roles = relations(
  payload_users_roles,
  ({ one }) => ({
    parent: one(payload_users, {
      fields: [payload_users_roles.parent],
      references: [payload_users.id],
      relationName: "roles",
    }),
  }),
);
export const relations_payload_users_sessions = relations(
  payload_users_sessions,
  ({ one }) => ({
    _parentID: one(payload_users, {
      fields: [payload_users_sessions._parentID],
      references: [payload_users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_payload_users = relations(payload_users, ({ many }) => ({
  roles: many(payload_users_roles, {
    relationName: "roles",
  }),
  sessions: many(payload_users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media_assets = relations(media_assets, ({ one }) => ({
  uploadedBy: one(payload_users, {
    fields: [media_assets.uploadedBy],
    references: [payload_users.id],
    relationName: "uploadedBy",
  }),
}));
export const relations_categories = relations(categories, ({ one }) => ({
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: "parent",
  }),
}));
export const relations_authors = relations(authors, ({ one }) => ({
  profileImage: one(media_assets, {
    fields: [authors.profileImage],
    references: [media_assets.id],
    relationName: "profileImage",
  }),
}));
export const relations_articles_rels = relations(articles_rels, ({ one }) => ({
  parent: one(articles, {
    fields: [articles_rels.parent],
    references: [articles.id],
    relationName: "_rels",
  }),
  authorsID: one(authors, {
    fields: [articles_rels.authorsID],
    references: [authors.id],
    relationName: "authors",
  }),
  categoriesID: one(categories, {
    fields: [articles_rels.categoriesID],
    references: [categories.id],
    relationName: "categories",
  }),
}));
export const relations_articles = relations(articles, ({ one, many }) => ({
  heroMedia: one(media_assets, {
    fields: [articles.heroMedia],
    references: [media_assets.id],
    relationName: "heroMedia",
  }),
  seoImage: one(media_assets, {
    fields: [articles.seoImage],
    references: [media_assets.id],
    relationName: "seoImage",
  }),
  _rels: many(articles_rels, {
    relationName: "_rels",
  }),
}));
export const relations_frontpage_slots = relations(
  frontpage_slots,
  ({ one }) => ({
    article: one(articles, {
      fields: [frontpage_slots.article],
      references: [articles.id],
      relationName: "article",
    }),
    mediaAsset: one(media_assets, {
      fields: [frontpage_slots.mediaAsset],
      references: [media_assets.id],
      relationName: "mediaAsset",
    }),
  }),
);
export const relations_reels = relations(reels, ({ one }) => ({
  mediaAsset: one(media_assets, {
    fields: [reels.mediaAsset],
    references: [media_assets.id],
    relationName: "mediaAsset",
  }),
  article: one(articles, {
    fields: [reels.article],
    references: [articles.id],
    relationName: "article",
  }),
}));
export const relations_tip_submissions = relations(
  tip_submissions,
  ({ one }) => ({
    assignedTo: one(payload_users, {
      fields: [tip_submissions.assignedTo],
      references: [payload_users.id],
      relationName: "assignedTo",
    }),
    relatedArticle: one(articles, {
      fields: [tip_submissions.relatedArticle],
      references: [articles.id],
      relationName: "relatedArticle",
    }),
  }),
);
export const relations_ad_campaigns = relations(ad_campaigns, ({ one }) => ({
  mediaAsset: one(media_assets, {
    fields: [ad_campaigns.mediaAsset],
    references: [media_assets.id],
    relationName: "mediaAsset",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    "payload-usersID": one(payload_users, {
      fields: [payload_locked_documents_rels["payload-usersID"]],
      references: [payload_users.id],
      relationName: "payload-users",
    }),
    "media-assetsID": one(media_assets, {
      fields: [payload_locked_documents_rels["media-assetsID"]],
      references: [media_assets.id],
      relationName: "media-assets",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: "authors",
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: "articles",
    }),
    "frontpage-slotsID": one(frontpage_slots, {
      fields: [payload_locked_documents_rels["frontpage-slotsID"]],
      references: [frontpage_slots.id],
      relationName: "frontpage-slots",
    }),
    reelsID: one(reels, {
      fields: [payload_locked_documents_rels.reelsID],
      references: [reels.id],
      relationName: "reels",
    }),
    "tip-submissionsID": one(tip_submissions, {
      fields: [payload_locked_documents_rels["tip-submissionsID"]],
      references: [tip_submissions.id],
      relationName: "tip-submissions",
    }),
    "ad-campaignsID": one(ad_campaigns, {
      fields: [payload_locked_documents_rels["ad-campaignsID"]],
      references: [ad_campaigns.id],
      relationName: "ad-campaigns",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    "payload-usersID": one(payload_users, {
      fields: [payload_preferences_rels["payload-usersID"]],
      references: [payload_users.id],
      relationName: "payload-users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_payload_users_roles: typeof enum_payload_users_roles;
  enum_media_assets_provider: typeof enum_media_assets_provider;
  enum_media_assets_type: typeof enum_media_assets_type;
  enum_media_assets_status: typeof enum_media_assets_status;
  enum_categories_existing_route: typeof enum_categories_existing_route;
  enum_articles_status: typeof enum_articles_status;
  enum_articles_access_level: typeof enum_articles_access_level;
  enum_frontpage_slots_placement: typeof enum_frontpage_slots_placement;
  enum_reels_status: typeof enum_reels_status;
  enum_tip_submissions_status: typeof enum_tip_submissions_status;
  enum_tip_submissions_risk_level: typeof enum_tip_submissions_risk_level;
  payload_users_roles: typeof payload_users_roles;
  payload_users_sessions: typeof payload_users_sessions;
  payload_users: typeof payload_users;
  media_assets: typeof media_assets;
  categories: typeof categories;
  authors: typeof authors;
  articles: typeof articles;
  articles_rels: typeof articles_rels;
  frontpage_slots: typeof frontpage_slots;
  reels: typeof reels;
  tip_submissions: typeof tip_submissions;
  ad_campaigns: typeof ad_campaigns;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_payload_users_roles: typeof relations_payload_users_roles;
  relations_payload_users_sessions: typeof relations_payload_users_sessions;
  relations_payload_users: typeof relations_payload_users;
  relations_media_assets: typeof relations_media_assets;
  relations_categories: typeof relations_categories;
  relations_authors: typeof relations_authors;
  relations_articles_rels: typeof relations_articles_rels;
  relations_articles: typeof relations_articles;
  relations_frontpage_slots: typeof relations_frontpage_slots;
  relations_reels: typeof relations_reels;
  relations_tip_submissions: typeof relations_tip_submissions;
  relations_ad_campaigns: typeof relations_ad_campaigns;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
